### ISSUE TITLE
Utilidades de Interface

### ISSUE THREAD

**Issue by l-ricardo** [UnBParadigmas2024-2/2024.2_G3_Funcional_Termo#3]
- [x] Implementar função para printar o texto estilizado com base no `LetterStatus`.
  - [x] Definir cores específicas para cada status (Untested, NoExist, WrongPlace, RightPlace).

**Comment by fellipepcs** [comment]
<img width="511" alt="image" src="https://github.com/user-attachments/assets/149e7658-f14a-44e5-a8ea-914ad5686ec1">
