### ISSUE TITLE
Atualização da Interface e Exibição de Jogo

### ISSUE THREAD

**Issue by l-ricardo** [UnBParadigmas2024-2/2024.2_G3_Funcional_Termo#6]
- [x] "Desenhar" a tela de jogo. 
  - [x] "Desenhar" o histórico de palavras ja testadas. (ver #2 e #3)
  - [x] "Desenhar" o alfabeto das letras já usadas com suas respectivas cores. (ver #2 e #3)

**Comment by AmandaNbr** [comment]
Adicionei o módulo Ansi, que muda as cores no terminal.
- [ver PR](https://github.com/UnBParadigmas2024-2/2024.2_G3_Funcional_Termo/pull/14)
- [documentação Ansi](https://hackage.haskell.org/package/ansi-terminal-0.5.0/docs/System-Console-ANSI.html)
