### ISSUE TITLE
Processamento do Input

### ISSUE THREAD

**Issue by l-ricardo** [UnBParadigmas2024-2/2024.2_G3_Funcional_Termo#9]
- [x] Implementar uma função que compara a palavra do jogador com a palavra secreta. (`processAttempt`)
  - [x] Atribuir para cada letra do input o valor de `RightPlace` (posição correta), `WrongPlace` (letra presente em posição incorreta) e `NoExist` (letras ausentes)
  - [x] Atualizar o registro do alfabeto e de tentativas (ver #2)
  - [x] Retornar os resultados da verificação para exibição ao jogador. (ver #10)

**Comment by Neitan2001** [comment]
Esse é meu
